name: Helm Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Kubernetes namespace name'
        required: true
      application:
        description: 'Application name (used for resource names and Helm release)'
        required: true
      repository:
        description: 'Container image repository (e.g., ghcr.io/your-name/app)'
        required: true
      tag:
        description: 'Image tag to deploy'
        required: true
      containerPort:
        description: 'Container port'
        required: true
        default: '80'
      domain:
        description: 'Domain name for ingress'
        required: true
      ingressClass:
        description: 'Ingress class name for internal app use `internal-nginx` and for external app `external-nginx`'
        required: true
      healthPath:
        description: 'Health check path for readiness probe'
        required: true
        default: '/healthz'

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: github-actions-session
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Twingate
        uses: twingate/github-action@v1
        with:
          service-key: ${{ secrets.TWINGATE_SERVICE_KEY_SECRET_NAME }}

      - name: Configure EKS kubeconfig
        uses: silverlyra/setup-aws-eks@v0.1
        with:
          cluster: ${{ secrets.CLUSTER_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create environment variable secret from JSON
        env:
          ENV_JSON: ${{ secrets.ENV_SECRET_JSON }}
          SECRET_NAME: ${{ github.event.inputs.application }}-secret
          NAMESPACE: ${{ github.event.inputs.namespace }}
        run: |
          echo "$ENV_JSON" > /tmp/env.json
          # Convert JSON to --from-literal flags
          LITERAL_ARGS=$(jq -r 'to_entries[] | "--from-literal=" + .key + "=" + .value' /tmp/env.json | xargs)
          # Create secret with dynamic name
          kubectl create namespace ${{ github.event.inputs.namespace }} --dry-run=client -o yaml | kubectl apply -f -
          eval kubectl create secret generic "$SECRET_NAME" \
            --namespace "$NAMESPACE" \
            $LITERAL_ARGS \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create imagePullSecret for private registry
        run: |
          kubectl create secret docker-registry regcred \
            --namespace ${{ github.event.inputs.namespace }} \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GHCR_TOKEN }} \
            --docker-email=you@example.com \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ github.event.inputs.application }} ./helm \
            --namespace ${{ github.event.inputs.namespace }} \
            --create-namespace \
            --set image.repository=${{ github.event.inputs.repository }} \
            --set image.tag=${{ github.event.inputs.tag }} \
            --set imagePullSecrets[0].name=regcred \
            --set containerPort=${{ github.event.inputs.containerPort }} \
            --set ingress.className=${{ github.event.inputs.ingressClass }} \
            --set ingress.hosts[0].host=${{ github.event.inputs.domain }} \
            --set ingress.hosts[0].paths[0].path=/ \
            --set ingress.hosts[0].paths[0].pathType=ImplementationSpecific \
            --set readinessProbe.httpGet.path=${{ github.event.inputs.healthPath }} \
            --set livenessProbe.httpGet.path=${{ github.event.inputs.healthPath }} \
            --set envSecret.name=${{ github.event.inputs.application }}-secret \
            --wait \
            --debug